### ISSUE TITLE
Bundling nanomsg and plans for this egg?

### ISSUE THREAD

**Issue by kiatoa** [Adellica/chicken-nanomsg#1]
The nanomsg project and this egg are very interesting to me. I would vote for bundling the library if it is easy to switch between the bundled library and a locally installed library.

I have an application where i was using pub -> sub and pull <- push with zmq. I'd like to try using the nanomsg egg but I'm not clear on what is already supported. Can you publish a road map of sorts? What are you plans for nanomsg?

Could you put together a few more samples to cover the implemented patterns?

Thanks!

**Comment by kristianlm** [comment]
Hi Kiatoa,

And thanks for your interest in this. Unfortunately, we are no longer using this egg in our project so we aren't really maintaining it anymore. Hency, no roadmap, really.

I have tried to rewrite the readme so it's more clear as to what's supported. I have also added all the missing protocol types, so now all pubsub, pipeline, reqrep, bus and survey should be supported.

I have added a `sample.pipeline.scm` which may help you get started - let me know if anything if unclear in that one.

And please keep me updated on how/if you end up using this!

**Comment by kristianlm** [comment]
Oh, and for bundling nanomsg, I have created a new branch `bundle-nanomsg` but I'm not happy with how it works. I think this may be a little tricky: the nanomsg sources have put a lot of effort into cross-compiling (and making it work on Windows, for example), and I'm not sure how to take advantage of that if we bundle it. I guess it could be bundled with everything and configure and compile a static version of nanomsg.

However, this approach may be a little fragile in case you have several different nanomsg applications which wouldn't be using the same nanomsg versions. Not sure how this should be handled.

**Comment by kiatoa** [comment]
Thanks so much! It is very helpful and I appreciate your effort. I think bundling is not so important if it gets complicated. Installing nanomsg is easy enough. If I may ask, were there issues or limitations with nanomsg that caused you to look at alternative solutions? 

I'll test out nanomsg for my application and comment back here on my findings then close this ticket.

**Comment by kiatoa** [comment]
I'm using rep/req and it seems to be working fine but for one problem (or is it a feature?). If I start two servers in parallel I expected one of them to fail. What I get is one succeeds and the other hangs. Is there something I need to do to have it throw an exception?

(define s (nn-socket 'rep))
(nn-bind rep "tcp://*:22022")

**Comment by kiatoa** [comment]
It looks like not raising an exception is the current behavior of the library: http://www.freelists.org/post/nanomsg/How-to-bind-on-a-random-port,18

For my application I'm able to work around the hang by having the server ping itself and shutdown if it can't talk to itself.

**Comment by kristianlm** [comment]
I think this isn't really something that can be fixed in the bindings, but the nature of nanomsg. Can we close?
