### ISSUE TITLE
Contrary to docs, not all protocols are supported

### ISSUE THREAD

**Issue by mgushee** [Adellica/chicken-nanomsg#2]
While learning to use the egg, I noticed that while the README claims that "all of nanomsg's protocols are supported", the pair and bus protocols are not supported. Specifically, the appropriate headers (<nanomsg/pair.h> & <nanomsg/bus.h>) are not included, and NN_PAIR and NN_BUS are not included in the 'nn-protocol' foreign enum type. It's not an urgent matter for me, but I thought I should point out the contradiction.

**Comment by mgushee** [comment]
I see that the above is not quite correct. The actual problem is that the source code I obtained with `chicken-install -r` was out of date.

**Comment by kristianlm** [comment]
Oh, I suppose I should make a new tag! Now let me see if I can get this right ...

I tried to release version 0.3, see if that works now with `chicken-install -r nanomsg`. Please close if my release worked :)

**Comment by kristianlm** [comment]
Assuming this has been fixed, closing.
