### ISSUE TITLE
Bad byte count for sent strings

### ISSUE THREAD

**Issue by werelax** [Adellica/chicken-nanomsg#3]
Strings sent with `nn-send` lose the final null byte.

``` scheme
(define (nn-send socket data #!optional (flags 0))
  (nn-assert ( (foreign-lambda int "nn_send" nn-socket blob int int)
              socket data (number-of-bytes data) flags)))
```

that `(number-of-bytes data)` should be `(+ 1 (number-of-bytes))` if data is a string.

**Comment by kristianlm** [comment]
No, CHICKEN strings aren't null-terminated. Which is nice because they can contain the null-byte:

```
$ csi -p '"\x00A"'| xxd
00000000: 0041 0a                                  .A.
```

If you want to send a null-terminated string you'll have to append it yourself (with `\x00` or something).

**Comment by werelax** [comment]
You're right. Sorry!
