### ISSUE TITLE
Can't run test suite due to missing sockopts.scm

### ISSUE THREAD

**Issue by caolan** [Adellica/chicken-nanomsg#6]
```
$ csi -s tests/run.scm

Error: (open-input-file) cannot open file - No such file or directory: "sockopts.scm"

...
```

Perhaps a file wasn't added to the git repository, or there was a setup step I missed?

**Comment by kristianlm** [comment]
This problem gets me so often! It's trying to include `sockopts.scm` from `.`, where it should be looking for it under the `./test` directory. I really wish `include` was `include-relative` by default. Why isn't it? So:

```
cd test
csi -s run.scm
```

This is what `chicken-install -s -test` must be doing since that's working.
